import { CardBackCosmetic, FontStyleCosmetic, TableSkinCosmetic } from './types';

export const CARD_BACKS: CardBackCosmetic[] = [
  {
    id: 'back-classic',
    name: 'Classic Blue',
    description: 'The standard card back every player starts with.',
    category: 'cardBack',
    unlock: { method: 'default', label: 'Owned' },
    previewColors: ['#1e3a8a', '#2563eb', '#93c5fd'],
    pattern: 'classic',
    primaryColor: '#1e3a8a',
    secondaryColor: '#2563eb',
    accentColor: '#93c5fd',
  },
  {
    id: 'back-royal',
    name: 'Royal Gold',
    description: 'Elegant gold filigree on deep burgundy.',
    category: 'cardBack',
    unlock: { method: 'rewarded_ad', label: 'Watch an ad to unlock' },
    previewColors: ['#4a0404', '#7f1d1d', '#fbbf24'],
    pattern: 'royal',
    primaryColor: '#4a0404',
    secondaryColor: '#7f1d1d',
    accentColor: '#fbbf24',
  },
  {
    id: 'back-midnight',
    name: 'Midnight Stars',
    description: 'A starfield pattern for night-owl players.',
    category: 'cardBack',
    unlock: { method: 'rewarded_ad', label: 'Watch an ad to unlock' },
    previewColors: ['#0f172a', '#1e293b', '#818cf8'],
    pattern: 'stars',
    primaryColor: '#0f172a',
    secondaryColor: '#1e293b',
    accentColor: '#818cf8',
  },
  {
    id: 'back-diamond',
    name: 'Diamond Weave',
    description: 'Unlock by winning 5 single-player hands.',
    category: 'cardBack',
    unlock: { method: 'single_player_win', label: 'Win 5 single-player hands', threshold: 5 },
    previewColors: ['#064e3b', '#059669', '#6ee7b7'],
    pattern: 'diamond',
    primaryColor: '#064e3b',
    secondaryColor: '#059669',
    accentColor: '#6ee7b7',
  },
  {
    id: 'back-waves',
    name: 'Ocean Waves',
    description: 'Unlock by winning 15 single-player hands.',
    category: 'cardBack',
    unlock: { method: 'single_player_win', label: 'Win 15 single-player hands', threshold: 15 },
    previewColors: ['#0c4a6e', '#0284c7', '#7dd3fc'],
    pattern: 'waves',
    primaryColor: '#0c4a6e',
    secondaryColor: '#0284c7',
    accentColor: '#7dd3fc',
  },
  {
    id: 'back-campaign-teal',
    name: 'Scholar Teal',
    description: 'Complete Campaign Level 10.',
    category: 'cardBack',
    unlock: { method: 'campaign_level', label: 'Complete Campaign Level 10', threshold: 10 },
    previewColors: ['#134e4a', '#0d9488', '#5eead4'],
    pattern: 'diamond',
    primaryColor: '#134e4a',
    secondaryColor: '#0d9488',
    accentColor: '#5eead4',
  },
  {
    id: 'back-campaign-ember',
    name: 'Ember Crest',
    description: 'Complete Campaign Level 40.',
    category: 'cardBack',
    unlock: { method: 'campaign_level', label: 'Complete Campaign Level 40', threshold: 40 },
    previewColors: ['#7c2d12', '#ea580c', '#fdba74'],
    pattern: 'royal',
    primaryColor: '#7c2d12',
    secondaryColor: '#ea580c',
    accentColor: '#fdba74',
  },
];

export const FONT_STYLES: FontStyleCosmetic[] = [
  {
    id: 'font-system',
    name: 'System Clean',
    description: 'Crisp and readable on every device.',
    category: 'fontStyle',
    unlock: { method: 'default', label: 'Owned' },
    previewColors: ['#1f2937', '#374151', '#6b7280'],
    fontFamily: 'System',
    rankScale: 1,
    suitScale: 1,
    letterSpacing: 0,
  },
  {
    id: 'font-playfair',
    name: 'Playfair Classic',
    description: 'Serif elegance inspired by vintage card rooms.',
    category: 'fontStyle',
    unlock: { method: 'rewarded_ad', label: 'Watch an ad to unlock' },
    previewColors: ['#292524', '#44403c', '#a8a29e'],
    fontFamily: 'PlayfairDisplay_700Bold',
    rankScale: 1.05,
    suitScale: 0.95,
    letterSpacing: 0.5,
  },
  {
    id: 'font-inter',
    name: 'Inter Modern',
    description: 'A sharp, modern look for competitive play.',
    category: 'fontStyle',
    unlock: { method: 'rewarded_ad', label: 'Watch an ad to unlock' },
    previewColors: ['#111827', '#1f2937', '#9ca3af'],
    fontFamily: 'Inter_600SemiBold',
    rankScale: 0.95,
    suitScale: 1,
    letterSpacing: -0.3,
  },
  {
    id: 'font-oswald',
    name: 'Oswald Bold',
    description: 'Unlock by reaching 500 cumulative single-player points.',
    category: 'fontStyle',
    unlock: {
      method: 'single_player_milestone',
      label: 'Score 500 points in single player',
      threshold: 500,
    },
    previewColors: ['#18181b', '#27272a', '#71717a'],
    fontFamily: 'Oswald_700Bold',
    rankScale: 1.1,
    suitScale: 1.05,
    letterSpacing: 1,
  },
  {
    id: 'font-campaign-serif',
    name: 'Campaign Classic',
    description: 'Complete Campaign Level 20.',
    category: 'fontStyle',
    unlock: { method: 'campaign_level', label: 'Complete Campaign Level 20', threshold: 20 },
    previewColors: ['#292524', '#44403c', '#a8a29e'],
    fontFamily: 'PlayfairDisplay_700Bold',
    rankScale: 1.05,
    suitScale: 0.95,
    letterSpacing: 0.5,
  },
];

export const TABLE_SKINS: TableSkinCosmetic[] = [
  {
    id: 'table-classic-green',
    name: 'Classic Felt',
    description: 'Traditional green baize table.',
    category: 'tableSkin',
    unlock: { method: 'default', label: 'Owned' },
    previewColors: ['#14532d', '#166534', '#22c55e'],
    feltStyle: 'classic',
    gradient: ['#0f3d22', '#166534', '#14532d'],
    railColor: '#3d2314',
    accentColor: '#fbbf24',
  },
  {
    id: 'table-midnight',
    name: 'Midnight Lounge',
    description: 'Dark felt for late-night sessions.',
    category: 'tableSkin',
    unlock: { method: 'rewarded_ad', label: 'Watch an ad to unlock' },
    previewColors: ['#0f172a', '#1e293b', '#334155'],
    feltStyle: 'midnight',
    gradient: ['#0f172a', '#1e293b', '#0f172a'],
    railColor: '#1c1917',
    accentColor: '#818cf8',
  },
  {
    id: 'table-royal',
    name: 'Royal Burgundy',
    description: 'Rich burgundy felt with gold rail.',
    category: 'tableSkin',
    unlock: { method: 'rewarded_ad', label: 'Watch an ad to unlock' },
    previewColors: ['#4c0519', '#881337', '#be123c'],
    feltStyle: 'royal',
    gradient: ['#4c0519', '#881337', '#4c0519'],
    railColor: '#292524',
    accentColor: '#fbbf24',
  },
  {
    id: 'table-ocean',
    name: 'Ocean Depths',
    description: 'Unlock by winning 10 single-player hands.',
    category: 'tableSkin',
    unlock: { method: 'single_player_win', label: 'Win 10 single-player hands', threshold: 10 },
    previewColors: ['#164e63', '#0e7490', '#22d3ee'],
    feltStyle: 'ocean',
    gradient: ['#164e63', '#0e7490', '#164e63'],
    railColor: '#1e3a5f',
    accentColor: '#67e8f9',
  },
  {
    id: 'table-vintage',
    name: 'Vintage Wood',
    description: 'Unlock by scoring 1,000 single-player points.',
    category: 'tableSkin',
    unlock: {
      method: 'single_player_milestone',
      label: 'Score 1,000 points in single player',
      threshold: 1000,
    },
    previewColors: ['#78350f', '#92400e', '#d97706'],
    feltStyle: 'vintage',
    gradient: ['#78350f', '#92400e', '#78350f'],
    railColor: '#451a03',
    accentColor: '#fcd34d',
  },
  {
    id: 'table-campaign-dusk',
    name: 'Dusk Felt',
    description: 'Complete Campaign Level 30.',
    category: 'tableSkin',
    unlock: { method: 'campaign_level', label: 'Complete Campaign Level 30', threshold: 30 },
    previewColors: ['#312e81', '#4338ca', '#818cf8'],
    feltStyle: 'midnight',
    gradient: ['#312e81', '#4338ca', '#312e81'],
    railColor: '#1e1b4b',
    accentColor: '#a5b4fc',
  },
  {
    id: 'table-campaign-gold',
    name: 'Champion Gold',
    description: 'Complete Campaign Level 50.',
    category: 'tableSkin',
    unlock: { method: 'campaign_level', label: 'Complete Campaign Level 50', threshold: 50 },
    previewColors: ['#713f12', '#a16207', '#fde047'],
    feltStyle: 'royal',
    gradient: ['#713f12', '#92400e', '#713f12'],
    railColor: '#292524',
    accentColor: '#fde047',
  },
];

export const ALL_COSMETICS = [...CARD_BACKS, ...FONT_STYLES, ...TABLE_SKINS];

export function getCosmeticById(id: string) {
  return ALL_COSMETICS.find((c) => c.id === id);
}

export function getCosmeticsByCategory(category: 'cardBack' | 'fontStyle' | 'tableSkin') {
  switch (category) {
    case 'cardBack':
      return CARD_BACKS;
    case 'fontStyle':
      return FONT_STYLES;
    case 'tableSkin':
      return TABLE_SKINS;
  }
}
